spring:
  application:
    name: parkourapi
  datasource:
    # The jdbc url is: jdbc:h2:mem:schoolapidb
    url: jdbc:h2:mem:parkourapidb;DB_CLOSE_DELAY=-1 # for In-memory database and jdbc:h2:file:[path/database-name] for disk-based database.
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    show-sql: true
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
  h2:
    console:
      enabled: true # The console url is: /h2-console
  ai:
    mistralai:
      api-key: ErMxwojLidaY1m7jndH5uOLJWV8gnCAj
      chat:
        options:
          model: mistral-small-latest
jwt:
  secret: jOkUI309fb6Lk6cBEzmf05NnPHXfST6EnvmWnGXoYk7VTT2g9a
  expiration: 3600000 # 1 hour
server:
  port: 8080
  forward-headers-strategy: framework